TheLudo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ludoapp.urls')),
]

ludoapp/urls.py
from django.conf import settings
# from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.urls import path
from . import views 

app_name = 'ludoapp'

urlpatterns = [
    path('', views.indexfirst, name='indexfirst'),
    path('indexlogin/', views.indexlogin, name='indexlogin'),
    path('landing/', views.landing, name='landing'),
    path('demo/', views.demo, name='demo'),
    path('demo/', views.demo, name='demo'),
    path('kyc/', views.kyc, name='kyc'),
    path('playerdetail/', views.playerdetail, name='playerdetail'),
    path('send_otp/', views.send_otp, name='send_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('profile/', views.edit_profile, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('wallet/', views.wallet, name='wallet'),
    path('history/', views.history, name='history'),
    path('index/', views.index, name='index'),
    path('login_page/', views.login_page, name='login_page'),
    path('registration_page/', views.registration_page, name='registration_page'),
    path('adminpanel/', views.adminpanel, name='adminpanel'),
    path('battle/', views.battle, name='battle'),
    path('battle', views.play_battle, name='play_battle'),
    path('accept/<int:battle_id>/', views.accept_battle, name='accept_battle'),
    path('policy/', views.policy, name='policy'),
    path('refer/', views.refer, name='refer'),
    path('support1/', views.support1, name='support1'),
    path('addmoney/', views.addmoney, name='addmoney'),
    path('approve/<str:phone>/', views.approve_player, name='approve_player'),
    path('delete/<str:phone>/', views.delete_player, name='delete_player'),
    path('share/whatsapp/', views.share_whatsapp, name='share_whatsapp'),
    path('share/telegram/', views.share_telegram, name='share_telegram'),
    path('copy_refer_code/', views.copy_refer_code, name='copy_refer_code'),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
    path('withdrawalaccount/', views.withdrawalaccount, name='withdrawalaccount'),
    # path('playbattle', views.playbattle, name='playbattle'),
    path('viewbattle/', views.viewbattle, name='viewbattle'),
    path('setbattle/', views.setbattle, name='setbattle'),
    path('battle_landing/', views.battle_landing, name='battle_landing'),
    # path('battle/', views.play_battle_view, name='play_battle_view'),
    path('accept_battle_view/', views.accept_battle_view, name='ludoapp:accept_battle_view'),
    path('delete_battle_view/', views.delete_battle_view, name='ludoapp:delete_battle_view'),
    # path('battle/', views.create_battle, name='create_battle'),
    # path('battle/play/<int:battle_id>/', views.play_battle, name='play_battle'),
    # path('battle/accept_or_abort/<int:battle_id>/', views.accept_or_abort_request, name='accept_or_abort_request'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add Django auth views for login and logout
# urlpatterns += [
#     path('accounts/login/', LoginView.as_view(), name='login_page'),  # Default Django login view
#     path('accounts/logout/', LogoutView.as_view(), name='logout'),  # Default Django logout view
# ]

ludoapp/models.py
# from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.

def validate_phone_length(value):
    if len(str(value)) != 10:
        raise ValidationError('Phone number must be 10 digits long.')


class player(models.Model):
    player_name = models.CharField(max_length=122)
    phone = models.BigIntegerField(validators=[validate_phone_length], primary_key=True)
    player_email = models.EmailField(max_length=122)
    password = models.CharField(max_length=122)
    confirm_password = models.CharField(max_length=122)
    front_image = models.ImageField(upload_to='images/',null=True)
    back_image = models.ImageField(upload_to='images/',null=True)
    wallet_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    approved = models.BooleanField(default=False)
    # kyc_status = models.CharField(max_length=20, default='pending')

    class Meta:
            db_table='player'
            ordering = ['player_name']


class Battle(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    is_running = models.BooleanField(default=False)
    creator = models.ForeignKey(player, related_name='created_battles', on_delete=models.CASCADE,default=None)
    opponent = models.ForeignKey(player, related_name='joined_battles', null=True, blank=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=20, default='open')  # open, requested, accepted
    # room_code = models.CharField(max_length=10, null=True, blank=True)


    def __str__(self):
        return f'Battle for ₹{self.amount} - {"Running" if self.is_running else "Open"}'


class withdrawalaccount(models.Model):
    player = models.ForeignKey(player, on_delete=models.CASCADE)
    withdraw_at = models.DateTimeField(auto_now_add=True)
    account_holder_name = models.CharField(max_length=255)
    upi_id = models.CharField(max_length=255)
    confirm_upi_id = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.account_holder_name} - {self.upi_id}"


    def is_expired(self):
        return timezone.now() > self.created_at + timedelta(minutes=1)

ludoapp/forms.py
from django import forms
from .models import player,Battle,withdrawalaccount
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    phone = forms.CharField(max_length=122)
    password = forms.CharField(widget=forms.PasswordInput)
    
class playerForm(forms.ModelForm):

    class Meta:
        model = player
        fields = ['player_name', 'phone', 'player_email', 'password', 'confirm_password']

class kycForm(forms.ModelForm):
    class Meta:
        model = player
        fields = ['front_image', 'back_image']

class BattleForm(forms.ModelForm):
    class Meta:
        model = Battle
        fields = ['amount']

class PlayBattleForm(forms.Form):
    battle_id = forms.IntegerField(widget=forms.HiddenInput())


class WithdrawalAccountForm(forms.ModelForm):
    class Meta:
        model = withdrawalaccount
        fields = ['account_holder_name','upi_id', 'confirm_upi_id', 'amount']

ludoapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.http import request
from django.views.generic import TemplateView
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from .models import player,Battle,withdrawalaccount
from django.contrib.auth.decorators import login_required
from .forms import playerForm, LoginForm,kycForm,BattleForm,PlayBattleForm ,WithdrawalAccountForm #,playForm
# from django.core.management.base import BaseCommand
# from celery import shared_task
# from celery.schedules import crontab
from django.utils import timezone
from datetime import timedelta
import urllib.parse




# Import your payment gateway API client (replace with your actual payment gateway library)
# from your_payment_gateway_library import PaymentGatewayClient

# class AddCashView(TemplateView):
#     template_name = 'add_cash.html'

#     def get(self, request, *args, **kwargs):
#         context = {
#             'amount': 0  # Initial amount, you can set this dynamically based on user input
#         }
#         return render(request, self.template_name, context)

#     def post(self, request, *args, **kwargs):
#         amount = request.POST.get('amount')

#         # Initialize your payment gateway client with your credentials
#         gateway_client = PaymentGatewayClient(
#             api_key=settings.PAYMENT_GATEWAY_API_KEY,
#             secret=settings.PAYMENT_GATEWAY_SECRET_KEY
#         )

#         # Example: Charge the user
#         payment_response = gateway_client.charge(amount)

#         # Check if payment was successful
#         if payment_response.success:
#             # Perform actions here like updating the user's wallet, logging the transaction, etc.
#             return redirect(reverse('ludoapp:wallet'))  # Redirect to wallet page after successful payment
#         else:
#             # Handle payment failure scenario
#             context = {
#                 'error_message': payment_response.error_message,
#                 'amount': amount
#             }
#             return render(request, self.template_name, context)




# class WithdrawCashView(TemplateView):
#     template_name = 'withdraw_cash.html'

#     def get(self, request, *args, **kwargs):
#         context = {
#             'amount': 0  # Initial amount, you can set this dynamically based on user input
#         }
#         return render(request, self.template_name, context)

#     def post(self, request, *args, **kwargs):
#         amount = request.POST.get('amount')

#         # Initialize your payment gateway client with your credentials
#         gateway_client = PaymentGatewayClient(
#             api_key=settings.PAYMENT_GATEWAY_API_KEY,
#             secret=settings.PAYMENT_GATEWAY_SECRET_KEY
#         )

#         # Example: Process withdrawal
#         withdrawal_response = gateway_client.withdraw(amount)

#         # Check if withdrawal was successful
#         if withdrawal_response.success:
#             # Perform actions here like updating the user's wallet, logging the transaction, etc.
#             return redirect(reverse('ludoapp:wallet'))  # Redirect to wallet page after successful withdrawal
#         else:
#             # Handle withdrawal failure scenario
#             context = {
#                 'error_message': withdrawal_response.error_message,
#                 'amount': amount
#             }
#             return render(request, self.template_name, context)


# class addmoney(TemplateView):
#     template_name = 'addmoney.html'

#     def get(self, request, *args, **kwargs):
#         return render(request, self.template_name)

#     def post(self, request, *args, **kwargs):
#         amount = request.POST.get('amount')

#         # Perform validation on amount (ensure it's a positive number)
#         try:
#             amount = float(amount)
#             if amount <= 0:
#                 raise ValueError("Amount must be positive")
#         except ValueError as e:
#             messages.error(request, str(e))
#             return redirect(reverse('ludoapp:addmoney'))

#         # Update user's wallet balance (assuming you have a Player model)
#         player = Player.objects.get(user=request.user)
#         player.wallet_balance += amount
#         player.save()

#         messages.success(request, f"Successfully added ${amount} to your wallet.")
#         return redirect(reverse('ludoapp:wallet'))














# Create your views here.
def refer(request):
    refer_code = '861335'  # Replace with your actual refer code
    context = {
        'refer_code': refer_code,
    }
    return render(request, 'refer.html', context)


from .utils import WhatsappRedirect
# Share via WhatsApp view
def share_whatsapp(request):
    refer_code = '861335'  # Replace with your actual refer code
    text = urllib.parse.quote(f"Use my refer code {refer_code} to join RK Ludo and earn rewards!")
    return WhatsappRedirect(f"whatsapp://send?text={text}")
    # return HttpResponseRedirect(f"whatsapp://send?text={text}")

# Share via Telegram view
def share_telegram(request):
    refer_code = '861335'  # Replace with your actual refer code
    text = urllib.parse.quote(f"Use my refer code {refer_code} to join RK Ludo and earn rewards!")
    return HttpResponseRedirect(f"https://telegram.me/share/url?url={text}")

# Copy refer code view
def copy_refer_code(request):
    refer_code = '861335'  # Replace with your actual refer code
    return render(request, 'copy_refer_code.html', {'refer_code': refer_code})

def battle_landing(request):
    return render(request, 'battle_landing.html')


# def create_battle(request):
    # if request.method == 'POST':
    #     form = BattleForm(request.POST)
    #     if form.is_valid():
    #         battle = form.save(commit=False)
    #         battle.save()
    #         return redirect('ludoapp:battle')  # Redirect to the landing page after creating the battle
    #     else:
    #         print("Form is not valid")
    #         print(form.errors)
    # else:
    #     form = BattleForm()

    # # battles = Battle.objects.filter(is_running=False)
    # return render(request, 'battle.html', {'form': form}) #, 'battles': battles})

# def landing(request):
#     # Delete expired battles
#     Battle.objects.filter(created_at__lt=timezone.now() - timedelta(minutes=1)).delete()

#     form = BattleForm()
#     battles = Battle.objects.filter(opponent__isnull=True)
#     return render(request, 'landing.html', {'form': form, 'battles': battles})

# @login_required
# def play_battle(request, battle_id):
#     battle = get_object_or_404(Battle, id=battle_id)
#     if not battle.opponent:
#         player = get_object_or_404(player, user=request.user)
#         battle.opponent = player
#         battle.save()
#         return redirect('accept_or_abort_request', battle_id=battle.id)
#     return redirect('battle_landing')

# @login_required
# def accept_or_abort_request(request, battle_id):
#     battle = get_object_or_404(Battle, id=battle_id)
#     if request.method == 'POST':
#         if 'accept' in request.POST:
#             battle.is_running = True
#             battle.room_code = request.POST.get('room_code')
#             battle.save()
#             return redirect('battle_landing')
#         elif 'abort' in request.POST:
#             battle.opponent = None
#             battle.save()
#             return redirect('battle_landing')
#     return render(request, 'battle/accept_or_abort.html', {'battle': battle})
# def approve_player(request, phone):
#     player = get_object_or_404(Player, id=phone)
#     if player.kyc_status != 'completed':
#         player.kyc_status = 'completed'
#         player.save()
#         messages.success(request, f'Player {player.phone} approved successfully.')
#     return redirect('ludoappp:playerdetail')  # Redirect to the list of players

# def delete_player(request, phone):
#     player = get_object_or_404(Player, id=phone)
#     if player.front_image:
#         player.front_image.delete()
#     if player.back_image:
#         player.back_image.delete()
#     player.delete()
#     player.kyc_status = 'completed'
#     messages.success(request, f'Player {player.phone} deleted successfully.')
#     return redirect('ludoapp:playerdetail')  # Redirect to the list of players

# import random

# def generate_otp():
#     return random.randint(100000, 999999)

# generate_otp()


# from django.shortcuts import render, redirect
# from django.http import JsonResponse
# # from .models import OTP
# # from .utils import generate_otp
def send_otp(request):
#     if request.method == 'POST':
#         phone_number = request.POST.get('phone_number')
#         otp = generate_otp()
#         # Save OTP to the database
#         OTP.objects.create(phone_number=phone_number, otp=otp)
#         # Mock sending OTP
#         print(f"Sending OTP {otp} to {phone_number}")
#         return JsonResponse({'message': 'OTP sent successfully'})
    return render(request, 'send_otp.html')

def verify_otp(request):
#     if request.method == 'POST':
#         phone_number = request.POST.get('phone_number')
#         otp = request.POST.get('otp')
#         otp_entry = OTP.objects.filter(phone_number=phone_number, otp=otp).first()
#         if otp_entry and otp_entry.is_valid():
#             otp_entry.is_used = True
#             otp_entry.save()
#             return JsonResponse({'message': 'OTP verified successfully'})
#         return JsonResponse({'message': 'Invalid OTP or OTP expired'})
    return render(request, 'verify_otp.html')



def index(request):
    return render(request,'index.html')


def policy(request):
    return render(request,'policy.html')

ludoapp/templates/kyc.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KYC Form</title>
</head>

<body>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }
        
        body {
            background: linear-gradient(135deg, #000000, #ff0000);
            animation: backgroundAnimation 5s infinite alternate;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        
        @keyframes backgroundAnimation {
            0% {
                background: linear-gradient(135deg, #000000, #ff0000);
            }
            100% {
                background: linear-gradient(135deg, #ff0000, #000000);
            }
        }
        
        .form-container {
            background: rgba(255, 255, 255, 0.9);
            padding: 20px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            width: 100%;
            max-width: 400px;
            animation: containerAnimation 1s ease-in-out;
        }
        
        @keyframes containerAnimation {
            0% {
                transform: scale(0.8);
                opacity: 0;
            }
            100% {
                transform: scale(1);
                opacity: 1;
            }
        }
        
        h2 {
            margin-bottom: 20px;
            text-align: center;
            color: #ff0000;
        }
        
        .form-group {
            margin-bottom: 15px;
        }
        
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #000000;
        }
        
        input[type="text"],
        input[type="email"],
        input[type="tel"],
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 14px;
            transition: border-color 0.3s ease;
        }
        
        input[type="text"]:focus,
        input[type="email"]:focus,
        input[type="tel"]:focus,
        input[type="file"]:focus {
            border-color: #ff0000;
        }
        
        button {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 5px;
            background: #ff0000;
            color: white;
            font-size: 16px;
            cursor: pointer;
            transition: background 0.3s ease;
        }
        
        button:hover {
            background: #d60000;
        }
    </style>
    <div class="form-container">
        <h2>KYC Form</h2>
        <form method="post" action="{% url 'ludoapp:kyc' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="mobile">Mobile No:</label>
                <input type="tel" id="phone" name="phone" pattern="[0-9]{10}" value="{{ phone }}" readonly required>
            </div>
            <div class="form-group">
                <label for="aadharFront">Aadhaar Front Image:</label>
                <input type="file" id="front_image" name="front_image" accept="image/*" required>
            </div>
            <div class="form-group">
                <label for="aadharBack">Aadhaar Back Image:</label>
                <input type="file" id="back_image" name="back_image" accept="image/*" required>
            </div>
            <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>

ludoapp/templates/support1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<!-- nevbarcss -->
<style>
    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
    }
    
    .topnav {
        overflow: hidden;
        background-color: #d60505ce;
    }
    
    .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }
    
    .topnav a:hover {
        background-color: #507288;
        color: black;
    }
    
    .topnav a.active {
        /* background-color: #507288; */
        /* color: 507288; */
    }
    
    .topnav .icon {
        display: none;
    }
    
    @media screen and (max-width: 600px) {
        .topnav a:not(:first-child) {
            display: none;
        }
        .topnav a.icon {
            float: left;
            display: block;
        }
    }
    
    @media screen and (max-width: 600px) {
        .topnav.responsive {
            position: relative;
        }
        .topnav.responsive .icon {
            position: absolute;
            right: 6;
            top: 0;
        }
        .topnav.responsive a {
            float: none;
            display: block;
            text-align: left;
            margin-left: -5px;
        }
    }
    
    .empty {
        display: block;
        margin-left: -100px;
    }
    /* Support Page style */
    
    * {
        margin: 0;
        box-sizing: border-box;
    }
    
    body {
        background-color: #6a9ac4;
    }
    
    #contact {
        background-color: #6a9ac4;
        display: flex;
        justify-content: right;
        align-items: center;
    }
    
    .contact-box {
        width: clamp(100px, 90%, 1000px);
        margin: 80px 50px;
        display: flex;
        flex-wrap: wrap;
    }
    
    .contact-links,
    .contact-form-wrapper {
        width: 50%;
        padding: 8% 5% 10% 5%;
    }
    
    .contact-links {
        background-color: #1f2e43;
        background: radial-gradient( circle at 55% 92%, #426691 0 12%, transparent 12.2%), radial-gradient( circle at 94% 72%, #426691 0 10%, transparent 10.2%), radial-gradient( circle at 20% max(78%, 350px), #263a53 0 7%, transparent 7.2%), radial-gradient( circle at 0% 0%, #263a53 0 40%, transparent 40.2%), #1f2e43;
        border-radius: 10px 0 0 10px;
    }
    
    .contact-form-wrapper {
        background-color: #ffffff8f;
        border-radius: 0 10px 10px 0;
    }
    
    @media only screen and (max-width: 800px) {
        .contact-links,
        .contact-form-wrapper {
            width: 100%;
        }
        .contact-links {
            border-radius: 10px 10px 0 0;
        }
        .contact-form-wrapper {
            border-radius: 0 0 10px 10px;
        }
    }
    
    @media only screen and (max-width: 400px) {
        .contact-box {
            width: 95%;
            margin: 8% 5%;
        }
    }
    
    h2 {
        font-family: 'Arimo', sans-serif;
        color: #fff;
        font-size: clamp(30px, 6vw, 60px);
        letter-spacing: 2px;
        text-align: center;
        transform: scale(.95, 1);
    }
    
    .links {
        display: grid;
        flex-wrap: wrap;
        justify-content: center;
        padding-top: 50px;
    }
    
    .link {
        margin: 10px;
        cursor: pointer;
    }
    
    img {
        width: 45px;
        height: 45px;
        filter: hue-rotate(220deg) drop-shadow(2px 4px 4px #0006);
        transition: 0.2s;
        user-select: none;
    }
    
    img:hover {
        transform: scale(1.1, 1.1);
    }
    
    img:active {
        transform: scale(1.1, 1.1);
        filter: hue-rotate(220deg) drop-shadow(2px 4px 4px #222) sepia(0.3);
    }
    
    .form-item {
        position: relative;
    }
    
    label,
    input,
    textarea {
        font-family: 'Poppins', sans-serif;
    }
    
    label {
        position: absolute;
        top: 10px;
        left: 2%;
        color: #999;
        font-size: clamp(14px, 1.5vw, 18px);
        pointer-events: none;
        user-select: none;
    }
    
    input,
    textarea {
        width: 100%;
        outline: 0;
        border: 1px solid #ccc;
        border-radius: 4px;
        margin-bottom: 20px;
        padding: 12px;
        font-size: clamp(15px, 1.5vw, 18px);
    }
    
    input:focus+label,
    input:valid+label,
    textarea:focus+label,
    textarea:valid+label {
        font-size: clamp(13px, 1.3vw, 16px);
        color: #777;
        top: -20px;
        transition: all .225s ease;
    }
    
    .submit-btn {
        background-color: #fd917e;
        filter: drop-shadow(2px 2px 3px #0003);
        color: #fff;
        font-family: "Poppins", sans-serif;
        font-size: clamp(16px, 1.6vw, 18px);
        display: block;
        padding: 12px 20px;
        margin: 2px auto;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        user-select: none;
        transition: 0.2s;
    }
    
    .submit-btn:hover {
        transform: scale(1.1, 1.1);
    }
    
    .submit-btn:active {
        transform: scale(1.1, 1.1);
        filter: sepia(0.5);
    }
    
    @media only screen and (max-width: 800px) {
        h2 {
            font-size: clamp(40px, 10vw, 60px);
        }
    }
    
    @media only screen and (max-width: 400px) {
        h2 {
            font-size: clamp(30px, 12vw, 60px);
        }
        .links {
            padding-top: 30px;
        }
        img {
            width: 38px;
            height: 38px;
        }
    }
    /* Support page end */
    /* Footer Style */
    
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    footer {
        display: flex;
        justify-content: space-around;
        align-items: center;
        padding: 10px 0;
        background-color: #4caf50;
        position: fixed;
        width: 100%;
        bottom: 0;
        left: 0;
    }
    
    .footer-button {
        background: none;
        border: none;
        color: white;
        font-size: 24px;
        cursor: pointer;
    }
    
    .footer-button:hover {
        color: #ddd;
    }
    /* Footer Style End */
</style>
<!-- nabvarcss -->
<!-- navbaehtmlscript -->

<body>
    <div class="topnav" id="myTopnav">
        <a class="empty"></a>
        <a href="{% url 'ludoapp:demo' %}" class="active">My profile</a>
        <a href="{% url 'ludoapp:landing' %}">Win cash</a>
        <a href="{% url 'ludoapp:wallet'%}">My Wallet</a>
        <a href="{% url 'ludoapp:demo'%}">Game History</a>
        <a href="#home" class="active">Transaction History</a>
        <a href="{% url 'ludoapp:refer' %}">Refer & Earn</a>
        <a href="#contact">Refer History</a>
        <a href="#about">Notification</a>
        <a href="{% url 'ludoapp:support1' %}">Support</a>
        <a href="{% url 'ludoapp:policy' %}">All Policies</a>
        <!-- <a href="#home" class="active">My profile</a>
        <a href="#news">Win cash</a>
        <a href="#contact">My Wallet</a>
        <a href="#about">Game History</a>
        <a href="#home" class="active">Transaction History</a>
        <a href="#news">Refer & Earn</a>
        <a href="#contact">Refer History</a>
        <a href="#about">Notification</a>
        <a href="#contact">Support</a>
        <a href="#about">All Policies</a> -->
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </div>
    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";  
            }
        }
    </script>

    <!-- Support Page body -->

    <body>
        <section id="contact">
            <div class="contact-box">
                <div class="contact-links">
                    <h2>CONTACT</h2>
                    <div class="links">
                        <div class="link">
                            <a><img src="{% static 'img/email.png' %}" alt="Mail"></a>
                        </div>
                        <div class="link">
                            <a><img src="{% static 'img/instagram.png' %}" alt="Instagram"></a>
                        </div>
                        <div class="link">
                            <a><img src="{% static 'img/telegram.png' %}" alt="Telegram"></a>
                        </div>
                        <div class="link">
                            <a><img src="{% static 'img/youtube.png' %}" alt="Youtube"></a>
                        </div>
                        <div class="link">
                            <a><img src="{% static 'img/whatsapp.png' %}" alt="Whatsapp"></a>
                        </div>
                    </div>
                </div>
                <!-- <div class="contact-form-wrapper">
              <form>
                <div class="form-item">
                  <input type="text" name="sender" required>
                  <label>Name:</label>
                </div>
                <div class="form-item">
                  <input type="text" name="email" required>
                  <label>Email:</label>
                </div>
                <div class="form-item">
                  <textarea class="" name="message" required></textarea>
                  <label>Message:</label>
                </div>
                <button class="submit-btn">Send</button>  
              </form>
            </div> -->
            </div>
        </section>
    </body>
    <!-- Support Page end -->

    <!-- Footer Start -->
    <footer>
        <a href="{% url 'ludoapp:landing' %}"><button class="footer-button" >
          <i class="fa fa-home"></i>
      </button></a>
        <a href="{% url 'ludoapp:wallet' %}"><button class="footer-button" >
          <i class="fa fa-phone"></i>
      </button></a>
        <a href="{% url 'ludoapp:support1' %}"><button class="footer-button" >
          <i class="fa fa-user"></i>
      </button></a>
    </footer>

    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <!-- Footer End -->
</body>
<!-- navbarhtmlscript -->

</html>